### ISSUE TITLE
Bib citation issue

### ISSUE THREAD

**Issue by zouharvi** [HKUNLP/instructor-embedding#10]
Hi, thanks for making the model publicly available. :slightly_smiling_face: 

I wanted to cite it so I used the provided bibtex entry:

```
@inproceedings{INSTRUCTOR,
  title={One Embedder, Any Task: Instruction-Finetuned Text Embeddings},
  author={Hongjin Su, Weijia Shi, Jungo Kasai, Yizhong Wang, Yushi Hu, Mari Ostendorf, Wen-tau Yih, Noah A. Smith, Luke Zettlemoyer, Tao Yu},
  url={https://arxiv.org/abs/2212.09741},
  year={2022},
}
```

However the Overleaf BibTeX installation is complaining that there are too many commas in the author list. My understanding is that it treats `and` as author separator and `,` as `last name, first names` separator.

Changing it to the following makes it work.

```
@inproceedings{INSTRUCTOR,
  title={One Embedder, Any Task: {I}nstruction-Finetuned Text Embeddings},
  author={Su, Hongjin and Shi, Weijia and Kasai, Jungo and Wang, Yizhong and Hu, Yushi and  Ostendorf, Mari and Yih, Wen-tau and Smith, Noah A. and  Zettlemoyer, Luke and Yu, Tao},
  url={https://arxiv.org/abs/2212.09741},
  year={2022},
}
```

**Comment by hongjin-su** [comment]
Thanks! The author list needs to be formatted and I have modified it accordingly!

**Comment by Harry-hash** [comment]
Feel free to re-open the issue if you have further comments/questions!
