### ISSUE TITLE
Code embeddings

### ISSUE THREAD

**Issue by shaileshj2803** [HKUNLP/instructor-embedding#13]
I would like to finetine this model for code embeddings. Have you tried this before. Any suggestions on how to proceed. Do we need hard negatives or we can use in batch negatives?

**Comment by Harry-hash** [comment]
Hi, Thanks a lot for your questions!

We included a few instances from https://huggingface.co/datasets/code_search_net in the INSTRUCTOR training. You may first try our training framework by following instructions here: https://github.com/HKUNLP/instructor-embedding#training. 

Optionally, you can mine the hard negatives for better performance (Here is a reference for hard negative mining pipeline: https://www.sbert.net/examples/training/ms_marco/README.html), but you can also use batch negatives by providing the `neg` field in the data with a random sampled pair from the dataset.

Hope this helps! Feel free to leave any further question or comment!

**Comment by Harry-hash** [comment]
Feel free to reopen this issue and add any following comments!

**Comment by bitnom** [comment]
> 

How many is "a few instances?" Also, were any characters/symbols omitted from the training data?
