### ISSUE TITLE
SummEval has incorrect description

### ISSUE THREAD

**Issue by ahoho** [HKUNLP/instructor-embedding#17]
Very minor problem, but I noticed that the description for [SummEval in MTEB was incorrect](https://github.com/embeddings-benchmark/mteb/pull/97), so the instructions in  [`SummarizationEvaluator.py`](https://github.com/HKUNLP/instructor-embedding/blob/edacd198edf7e8d1885df8fdc94c582d5a5c6fe0/evaluation/MTEB/mteb/evaluation/evaluators/SummarizationEvaluator.py#L16) should also be changed.

**Comment by Harry-hash** [comment]
Hi, thanks a lot for the reminder! I have updated the instructions!

**Comment by Harry-hash** [comment]
Feel free to reopen the issue if there is any further question or comment!
