### ISSUE TITLE
Does embedding pooling include instructions?

### ISSUE THREAD

**Issue by nbroad1881** [HKUNLP/instructor-embedding#18]
In section 2.1 of your paper, you indicate
> Given an input text x and a task instruction I_x, INSTRUCTOR encodes their concatenation Ix ⊕ x. We then generate a fixed-sized, task-specific embedding E_I (I_x, x) by applying mean pooling to the last hidden representations over the tokens in x

I interpret this to mean that you average only over x and ignore the instruction embeddings.

I see two different kinds of model definitions in this repo: [INSTRUCTOR_Transformer](https://github.com/HKUNLP/instructor-embedding/blob/4487f9ca0cee01b46622bf6b33e9c842028c1260/InstructorEmbedding/instructor.py#L221) and [INSTRUCTOR](https://github.com/HKUNLP/instructor-embedding/blob/4487f9ca0cee01b46622bf6b33e9c842028c1260/InstructorEmbedding/instructor.py#L388). It looks like the first one averages over x only and the second one will average over the instruction and x. Any reason why the second model averages over the whole sequence instead of just x?  It appears that INSTRUCTOR_Transformer is not used anywhere else in this repo.

**Comment by Harry-hash** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR model!

Your understanding of our pooling method is correct: we only average token embeddings over x and ignore the instruction embeddings. 

The INSTRUCTOR model is the model we use for embedding calculation, while INSTRUCTOR_Transformer is a module of it. In the method [_load_sbert_model](https://github.com/HKUNLP/instructor-embedding/blob/4487f9ca0cee01b46622bf6b33e9c842028c1260/InstructorEmbedding/instructor.py#L441) of the class INSTRUCTOR, you may see that several modules are loaded, including INSTRUCTOR_Transformer and INSTRUCTOR_Pooling. 

Hope this helps! Feel free to add any further question or comment!

**Comment by nbroad1881** [comment]
I see now. That makes sense. Thanks for the quick answer!
