### ISSUE TITLE
Trouble running training jobs

### ISSUE THREAD

**Issue by alexmoini** [HKUNLP/instructor-embedding#19]
Hi HKUNLP,

First off, really awesome paper on leveraging instructions to improve embedding quality across domains and tasks.

I am trying to train a model by following the directions to train a model. I downloaded the MTEB dataset, installed the requirements and am running the train job and continue to run into this error:
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.

Any idea why this is happening?

Thanks!

**Comment by Harry-hash** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR model!

You may want to download the [MEDI data](https://drive.google.com/file/d/1vZ5c2oJNonGOvXzppNg5mHz24O6jcc52/view?usp=sharing) instead of the MTEB data for training a model. 

Feel free to add any further question or comment!

**Comment by alexmoini** [comment]
Hi Harry,

Yeah that was a semantic mistake, I was using MEDI data.

Thanks,
Alex

**Comment by Harry-hash** [comment]
Feel free to reopen the issue if there is any further question or comment!
