### ISSUE TITLE
Path to contributing to sentence-transformers upstream?

### ISSUE THREAD

**Issue by creatorrr** [HKUNLP/instructor-embedding#2]
Kudos for the amazing work and hitting the top of the leaderboard! Thoughts on how to contribute changes to sentence-transformers upstream?

**Comment by Harry-hash** [comment]
Hi, thanks for your interest!

Currently we include sentence-transformers package in the code. You may modify the codes in `sentence-transformers` to make changes. In the future, we are considering writing a separate library for easier use.

Feel free to leave further questions or comments here!

**Comment by creatorrr** [comment]
Thanks @Harry-hash ! That make sense however for deploying this to production anywhere, the current workflow of cloning the lib is far from ideal. It'd be nice to contribute the changes back to `sentence-transformers` and then package this into a standalone library. Maybe if you can point me to a list of changes you've made to included libs, I could work on a PR?

**Comment by nickmuchi87** [comment]
Good point, have also been investigating how to clone and install the library from a HF Space as the usual git+http... has not been working for me.

**Comment by creatorrr** [comment]
@Harry-hash could you please do me a favor and post a list of changes that were made to the sources for `transformers/` and `sentence-transformers/` directories included in this repo?

If they aren't too big of a changes, we could figure out if monkey-patching could work and if not, we could make PRs to the upstream repos. This would be a hug help! 🙏

**Comment by Harry-hash** [comment]
Thanks a lot for all of your suggestions!

I have updated the code structure. The INSTRUCTOR can be now installed via pip, i.e.
```
pip install InstructorEmbedding
```
or directly from the source
```
pip install -e .
```

Check our updated README for more details, and feel free to leave your further questions here!

**Comment by Harry-hash** [comment]
Feel free to reopen the issue
