### ISSUE TITLE
Install MTEB

### ISSUE THREAD

**Issue by staoxiao** [HKUNLP/instructor-embedding#20]
Hi, 
Great work! I'm trying to reproduce the evaluation results on MTEB, but there occurs an error when I install the evaluation/MTEB following this command `cd evaluation/MTEB  pip install -e .` : 
 OSError: [Errno 2] No such file or directory: '/tmp/tmpni4r6sx4/output.json
![image](https://user-images.githubusercontent.com/29973524/225300532-37120a64-9e8c-4b2f-bdcb-c58e4110fd54.png)

Can you give some advice to fix this error? Thank you!

**Comment by Harry-hash** [comment]
Hi, Thanks a lot for your interest in INSTRUCTOR!

Regarding the error, you may try the following:
1. install the mteb package in a virtual environment, e.g., conda
2. check if you have access to /tmp directory
3. try `pip install mteb`, which is a package with similar install requirement, but different implementation.

Hope this helps! Feel free to add any further questions or comments!

**Comment by sherlcok314159** [comment]
`pip install mteb` can simply work.

**Comment by Harry-hash** [comment]
Feel free to reopen the issue if you have further questions or comments!
