### ISSUE TITLE
Multilingual capabilities

### ISSUE THREAD

**Issue by debraj135** [HKUNLP/instructor-embedding#23]
Dead authors, 

It was a delight to read your work on instruction fine-tuned embeddings. 

Are there any plans for extending the capabilities to a multilingual setup?

**Comment by Harry-hash** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR model!

We may decide not to further extend the model for the multilingual setup and will leave it as a future work.

Feel free to add further questions or comments

**Comment by Harry-hash** [comment]
Feel free to reopen this issue if you have any further questions or comments!

**Comment by debraj135** [comment]
Thank you so much for getting back to me. 

By the way I wanted to understand from you if the license is Apache 2.0. I see it mentioned on the huggingface model card.

**Comment by debraj135** [comment]
@Harry-hash please do let me know if you prefer to open a separate issue for my last comment.

**Comment by Harry-hash** [comment]
Hi, Thanks a lot for your reminder!

I have included the Apache-2.0 license for both codes and checkpoints. Feel free to check it out!
