### ISSUE TITLE
Set embedding vector dimension

### ISSUE THREAD

**Issue by masdelivery** [HKUNLP/instructor-embedding#24]
Hi, how are you?
Is there a way to set the dimension of the returned vector or is always fixed to 768?
(I'm very new to this)

Thanks,
Fran

**Comment by Harry-hash** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR model!

The dimension of the returned vector is fixed to 768.

Feel free to add further questions or comments!

**Comment by Harry-hash** [comment]
Feel free to re-open the issue if you have further questions or comments!
