### ISSUE TITLE
chinese support?

### ISSUE THREAD

**Issue by okideal** [HKUNLP/instructor-embedding#26]
Have the model trained on some chinese corpus dataset?

**Comment by Harry-hash** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR model!

As the INSTRUCTOR model is only trained on English texts, it may not support multilingual settings for now.

Feel free to contribute if you trained another version in Chinese or multilingual settings!

**Comment by Harry-hash** [comment]
Feel free to re-open the issue if you have any further question or comments!
