### ISSUE TITLE
hard coding problem of max sequence length 

### ISSUE THREAD

**Issue by silverstar0727** [HKUNLP/instructor-embedding#27]
Due to this [line](https://github.com/HKUNLP/instructor-embedding/blob/00948fb913b14a7e1e12e86df7f764b024ddafc7/InstructorEmbedding/instructor.py#L246), even if I run the code below, I still got max_seq_length fixed at 512.
`model.max_seq_length = 1024`

Is it because I can't change the max_seq_length?
If not, it would be right to erase this line.

**Comment by silverstar0727** [comment]
oh.... This line tricked me into believing that max_seq_length is 512...

I got a 1024 when I ran `print(model.max_seq_length)` and it's actually right.

**Comment by Harry-hash** [comment]
Yes, the line you mentioned is only for the initialization, and you can change the maximum sequence length by overriding it.
