### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dakinggg** [HKUNLP/instructor-embedding#28]
Hi, there is no license in this repo, and I was wondering if you would consider adding an explicit license? (Hopefully apache or other friendly license :)) Thanks, and thanks for the awesome work!

**Comment by Harry-hash** [comment]
Hi, Thanks a lot for your reminder!

I have included the Apache-2.0 license for both codes and checkpoints. Feel free to check it out!

**Comment by dakinggg** [comment]
Thanks so much!
