### ISSUE TITLE
hard negative dataset

### ISSUE THREAD

**Issue by Rabrg** [HKUNLP/instructor-embedding#3]
is the dataset used in the [hard negative commit changes](https://github.com/HKUNLP/instructor-embedding/commit/753786e85b0abf7fa80cdd49ed919621db255bdb) available for download somewhere?

i'm assuming the MEDI instructions are different from the dataset originally released, since the eval instructions are different (e.g. dropping `; Input:`)

**Comment by Harry-hash** [comment]
Hi, the dataset with hard negative is now available for download here: https://drive.google.com/file/d/1_Ax8rTeeDKpNxj85LD2Yh7qsh3sYEiSH/view?usp=sharing

Thanks a lot for your interests! Feel free to leave your further questions!

**Comment by Rabrg** [comment]
thank you! great work with the paper :)
