### ISSUE TITLE
Is it possible to use the Instructor model directly via sentence-transformers?

### ISSUE THREAD

**Issue by doraui** [HKUNLP/instructor-embedding#33]
It would be very useful, e.g. to train a cross-encoder.

**Comment by Harry-hash** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR model!

As we modified some classes in the sentence-transformers, you may find it more convenient to install both sentence-transformers and InstructorEmbedding for using the INSTRUCTOR model. 

To score sentence pairs, you may use the INSTRUCTOR models to compute the similarities between sentence pairs. Check out our example here: https://github.com/HKUNLP/instructor-embedding#compute-similarities-between-texts

Feel free to add any further questions or comments!

**Comment by hongjin-su** [comment]
Feel free to re-open the issue if you have any further questions or comments!
