### ISSUE TITLE
Is it possible to use instructor without instructions?

### ISSUE THREAD

**Issue by jlia0** [HKUNLP/instructor-embedding#35]
How will the model perform if not providing instructions or just some general instructions without giving the 1) domain, 2) text type, 3) text objective? Which one is the most important?

**Comment by aamir-s18** [comment]
Yes, it is. Just pass it usually as you do with sentence transformers. I think the MTEB results are also achieved without the instructions.

**Comment by Harry-hash** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR model!

The model may degrade to a general encoder if no instruction is provided. The instruction components are important, but you may skip one or two parts if the context is ambiguous and hard to determine.

Feel free to add any further questions or comments!

**Comment by jlia0** [comment]
Is there a way to do few-shot examples on the instruction side? Or is it a future work?

**Comment by syonfox** [comment]
Is there a way to have another model generate the instructions based on the text?

**Comment by hongjin-su** [comment]
Yes, I think it is possible to prompt ChatGPT or GPT-4 to summarize the domain, task type and task objective for the instruction

**Comment by syonfox** [comment]
Colud this have similar performance in the backend to a summarization and embedding approche

Ie are the instructions embeded and the distance is reduced by the use of a more simaler / regular output.  My question is if you know how important the instruction schema matching. is 

Could wildly verbose instructions be used to increase simalarity. 

But yeah gpt3.5 can do that in a few tokens hopfully.  Its probably hard codable. as well there are only so many options but i suspect include 

"What is the domain and important relavent information.  generate a json object with keys {domain, summary, questions, extrapolation, resorces}" with the subject domain or field, a sumary of the data, any  questions people might ask about this, an extrapolation of this based on training data and any aditional resoces you recomend looking up for more info and facts."

**Comment by hongjin-su** [comment]
You may refer to the table 5 in the [paper](https://arxiv.org/pdf/2212.09741.pdf) for examples of words in each field.

**Comment by hongjin-su** [comment]
Feel free to re-open the issue if you have any further questions or comments!
