### ISSUE TITLE
multilingual model

### ISSUE THREAD

**Issue by carlesoctav** [HKUNLP/instructor-embedding#40]
Thank you for this wonderful model. I have a question for you: Do you have any plans to develop a multilingual version of INSTRUCTOR?

**Comment by hongjin-su** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR model!

We may not develop the multilingual version of INSTRUCTOR for the time being, and we welcome all community contributions!

**Comment by MentalGear** [comment]
Would be important to clearly state this in the readme / model card.
