### ISSUE TITLE
Model Fine-tune for Classification Mission?

### ISSUE THREAD

**Issue by MrRabbit12** [HKUNLP/instructor-embedding#44]
Hello! There is an automatic classification mission for engineering construction safe cases, we want to fine-tune your model using our dataset. However, no specification was found on your web page. Could you please tell me HOW to do that?

**Comment by hongjin-su** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR model!

To further finetune the INSTRUCTOR model and apply it to classification task, you may connect an additional classifier to the sentence embeddings, and finetune either only the classifier or the whole model.

Feel free to add any further questions or comments!

**Comment by MrRabbit12** [comment]
thank u！！！！！！！This REALLY SOLVED my problem~
&nbsp;


山水
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月5日(星期一) 下午3:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HKUNLP/instructor-embedding] Model Fine-tune for Classification Mission? (Issue #44)





 
Hi, Thanks a lot for your interest in the INSTRUCTOR model!
 
To further finetune the INSTRUCTOR model and apply it to classification task, you may connect an additional classifier to the sentence embeddings, and finetune either only the classifier or the whole model.
 
Feel free to add any further questions or comments!

**Comment by hongjin-su** [comment]
Please re-open the issue if you have any questions or comments!
