### ISSUE TITLE
Why use DataCollatorForSeq2Seq to collect data?

### ISSUE THREAD

**Issue by tsotfsk** [HKUNLP/instructor-embedding#47]
I think this is a text retrieval task. Why use the seq2seq approach to construct the data?

**Comment by hongjin-su** [comment]
Hi, Thanks for your interest in the INSTRUCTOR!

The INSTRUCTOR is an embedding model for general purpose, and it performs quite well in the retrieval tasks. Could you help to provide more contexts about which part of data collection you are referring to?

**Comment by hongjin-su** [comment]
Please re-open the issue if your have any questions or comments!
