### ISSUE TITLE
docs: instructions syntax

### ISSUE THREAD

**Issue by greenpau** [HKUNLP/instructor-embedding#48]
Here is what I have noted for myself.

The syntax to write instructions: "Represent the `domain` `text_type` for `task_objective`: ", where:
* `domain` is optional, and it specifies the domain of the text, e.g., science, finance, medicine, etc.
* `text_type` is **required**, and it specifies the encoding unit, e.g., sentence, document, paragraph, etc.
* `task_objective` is optional, and it specifies the objective of embedding, e.g., retrieve a document, classify the sentence, etc.

The questions:
1. what is the exhaustive list of possible values for `domain`?
2. what is the exhaustive list of possible values for `text_type`?
3. what is the exhaustive list of possible values for `task_objective`?

**Comment by greenpau** [comment]
Awesome work! 👍 Thank you for the models!

**Comment by hongjin-su** [comment]
Hi, Thanks a lot for your interest in the INSTRUCTOR!

Although it may be hard to exhaustively list all possible values of domain, test type and task objective, we provide some examples in the table 4 of [our paper](https://arxiv.org/pdf/2212.09741.pdf).

Feel free to add more questions or comments!

**Comment by greenpau** [comment]
@hongjin-su , thank you!

The info I was looking for.

```py
domain = [
  'wikipedia',
  'news',
  'medicine',
  'biology',
  'reddit',
  'stackoverflow',
  'science',
  'quora',
  'coronavirus',
  'math',
  'physics'
]

text_type = [
  'question',
  'query',
  'answer',
  'summary',
  'sentence',
  'review',
  'post',
  'comment',
  'statement',
  'paragraph',
  'passage',
  'document'
] 

task_objective = [
  'classify the sentence as positive or negative',
  'retrieve a duplicate sentence',
  'retrieve the supporting document'
]
```
