### ISSUE TITLE
can I implement this code in google colab?

### ISSUE THREAD

**Issue by sanam077** [HKUNLP/instructor-embedding#5]
https://github.com/HKUNLP/instructor-embedding/blob/39a590f431b028cbcc61f0e914e26e39de6f7a2a/InstructorEmbedding/instructor.py#L28

**Comment by Harry-hash** [comment]
Sure! We provide a demo in Google Colab. You can easily try INSTRUCTOR here: https://colab.research.google.com/drive/1P7ivNLMosHyG7XOHmoh7CoqpXryKy3Qt?usp=sharing

**Comment by Harry-hash** [comment]
Feel free to re-open the issue if you have further comments/questions!
