### ISSUE TITLE
special tokens in tokenizer

### ISSUE THREAD

**Issue by erlakshmi123** [HKUNLP/instructor-embedding#56]
hi,

Is it possible to add special tokens to the tokenizer and retrain for a domain specific task?

**Comment by hongjin-su** [comment]
Yes, it is possible. You may add special tokens via `tokenizer.add_special_tokens(special_tokens)` and follow the [instruction](https://github.com/HKUNLP/instructor-embedding#training) to train the model.

**Comment by hongjin-su** [comment]
Please re-open the issue if you have any questions or comments!
