### ISSUE TITLE
Other model support.

### ISSUE THREAD

**Issue by staticpunch** [HKUNLP/instructor-embedding#57]
Hi, I would like to train an Instructor model for my language (Vietnamese), which is not supported by T5/GTR. Could I just use the code in this repo to finetune a pretrained model of my language (BERT/RoBERTa like) with my custom data?

**Comment by Harry-hash** [comment]
Yes, it is possible to use the other models with transformer architectures!

**Comment by hongjin-su** [comment]
Please re-open the issue if you have any questions or comments!
