### ISSUE TITLE
Plans for releasing distilled or smaller models than base* ?

### ISSUE THREAD

**Issue by amatanasov** [HKUNLP/instructor-embedding#6]
Congrats for the awesome work! Any plans in the future "distilling" the models?

**Comment by Harry-hash** [comment]
Thanks a lot for your interest in INSTRUCTOR!

Although it is possible to train a model smaller than base that follows instructions in some specific task/domain, we may leave it as future work.

**Comment by Harry-hash** [comment]
Feel free to re-open the issue if you have further comments/questions!
