### ISSUE TITLE
Install fails, dependencies don't get installed

### ISSUE THREAD

**Issue by koaning** [HKUNLP/instructor-embedding#7]
I installed this package via: 

```
pip install InstructorEmbedding
```

Then I try to run the quickstart. However, this yields an error on import. 

```
---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-2-479956c3d0e9>](https://localhost:8080/#) in <module>
----> 1 from InstructorEmbedding import INSTRUCTOR
      2 model = INSTRUCTOR('hkunlp/instructor-large')
      3 sentence = "3D ActionSLAM: wearable person tracking in multi-floor environments"
      4 instruction = "Represent the Science title:"
      5 

1 frames

[/usr/local/lib/python3.8/dist-packages/InstructorEmbedding/instructor.py](https://localhost:8080/#) in <module>
      7 from tqdm.autonotebook import trange
      8 from torch import Tensor, device
----> 9 from sentence_transformers import SentenceTransformer
     10 from sentence_transformers.models import Transformer
     11 from transformers import AutoConfig

ModuleNotFoundError: No module named 'sentence_transformers'
```

It seems this project doesn't install it's dependencies.

**Comment by Harry-hash** [comment]
Thanks a lot for your interest in INSTRUCTOR!

We do not force all the dependency installation/updates together with the InstructorEmbedding package. Instead, you can easily get all the dependencies installed via the following command
```
pip install -r requirements.txt
```

Hope this helps! Feel free to ask for further clarifications if there is any unclear part!

**Comment by koaning** [comment]
That could be fine, but then I would advice you update the text in [the getting started](https://github.com/HKUNLP/instructor-embedding#getting-started) section. As is, the example doesn't run after the provided installation instructions.

**Comment by Harry-hash** [comment]
Feel free to re-open the issue if you have further comments/questions!
