### ISSUE TITLE
 Multi-gpu evaluation

### ISSUE THREAD

**Issue by memray** [HKUNLP/instructor-embedding#8]
Hi there,

Is there a way to evaluate models with multiple GPUs? It is intimidating to run over large datasets.

Thanks,
Rui

**Comment by Harry-hash** [comment]
Thanks a lot for your interest in INSTRUCTOR!

We follow the evaluation of MTEB benchmark, which uses a single GPU by default. For multi-GPU evaluation on retrieval tasks, you may refer to [beir repo](https://github.com/beir-cellar/beir) for details.

Hope this helps!

**Comment by Harry-hash** [comment]
Feel free to re-open the issue if you have further comments/questions!
