### ISSUE TITLE
How influential is the "domain" and "task_objective" of each instruction on new data?

### ISSUE THREAD

**Issue by dcruiz01** [HKUNLP/instructor-embedding#9]
Hey Team, thank you for the awesome project and for sharing it with the wider community.

I have a question regarding the optimal strategy for attaching instructions to text we plan on embedding with InstructOR. If I have a set of documents I wish to embed, specifically for information retrieval, what would be the best way to write the instructions for these new documents and queries?

Additional Context:

In the appendices of your paper, I see that retrieval instructions were frequently tailored to the training dataset in question (e.g. for the gooaq_pairs dataset, you refer to each document as a "Google answer for retrieval"). This makes sense for training, but now for inference on new data, how much does the `domain` and `task_objective` influence the resulting embeddings? I see they are both optional parts of the unified template, but the examples you provide have domains and objectives that range from general "science sentence" to specific "Wikipedia question".

I figure using domains & task objectives leads to more specialized embeddings, but is there a curated list of domains/objectives somewhere to help guide end users?

Thanks for your time!

**Comment by Harry-hash** [comment]
Thanks a lot for your interest in INSTRUCTOR!

The domain and task objective in the instruction are important to the quality of text embeddings. We have some suggestions about the domain, text type and task objectives in the table 5 of [the paper](https://arxiv.org/abs/2212.09741). In general, you may refer to the data documentation/description for detailed information.

Hope this helps! Feel free to leave your further questions or comments here!

**Comment by dcruiz01** [comment]
@Harry-hash thank you for the feedback. I reviewed the paper but missed that small table. Much appreciated!
